# Generated by Django 3.0.7 on 2020-06-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=600)),
                ('Email', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=20)),
                ('Track', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Point', models.CharField(max_length=20)),
            ],
        ),
    ]
