# Generated by Django 3.0.7 on 2020-06-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10)),
                ('track', models.CharField(choices=[('design', 'Design'), ('frontend', 'Frontend'), ('backend', 'Backend')], default='backend', max_length=10)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'Javascript'), ('java', 'Java'), ('Go', 'Go'), ('Php', 'Php')], default='python', max_length=10)),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
