# Generated by Django 3.0.7 on 2020-06-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('track', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=10)),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
